// config.js
const config = {
  BASE_URL: "https://api.weatherapi.com",
  LOCATION: "indonesia",
  translations: {
    en: {
      search: "Search Location...",
      sub_text: "Weather Details...",
      temperature: "Temperature",
      feels_like: "Feels Like",
      humidity: "Humidity",
      cloudy: "Cloudy",
      wind: "Wind",
      name: "Name",
      departure: "Departure",
      departure_weather: "Departure Weather",
      destination: "Destination",
      destination_weather: "Destination Weather",
      date: "Date",
      notes: "Notes",
      action: "Action",
      btn_delete: "Delete",
      name_placeholder: "Name",
      departure_placeholder: "Departure",
      destination_placeholder: "Destination",
      notes_placeholder: "Notes...",
      add_placeholder: "Add",
      save_placeholder: "Save",
    },
    id: {
      search: "Cari Lokasi...",
      sub_text: "Detail Cuaca...",
      temperature: "Suhu",
      feels_like: "Suhu Terasa",
      humidity: "Kelembapan",
      cloudy: "Berawan",
      wind: "Kecepatan Angin",
      name: "Nama",
      departure: "Pemberangkatan",
      departure_weather: "Cuaca Pemberangkatan",
      destination: "Tujuan",
      destination_weather: "Cuaca Tujuan",
      date: "Tanggal",
      notes: "Catatan",
      action: "Aksi",
      btn_delete: "Hapus",
      name_placeholder: "Nama",
      departure_placeholder: "Pemberangkatan",
      destination_placeholder: "Tujuan",
      notes_placeholder: "Catatan...",
      add_placeholder: "Tambah",
      save_placeholder: "Simpan",
    },
  },
};

export default config;
